/*
 * generated by Xtext 2.24.0
 */
package entities.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EntityDslStandaloneSetup extends EntityDslStandaloneSetupGenerated {

	public static void doSetup() {
		new EntityDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
