grammar entities.dsl.EntityDsl with org.eclipse.xtext.common.Terminals
import "entities.entityModel"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
Entities:
 (declarations+=Declaration)*;
Declaration returns NamedType: PrimitiveType | Entity;
PrimitiveType:
 'datatype' name=ID
;
Entity:
 'entity' name=ID ('extends' baseEntity=[Entity])? '{'
 (fields+=Field)*
 '}';
Field:
 (array?='many')? name=ID ':' dataType=[NamedType];