/*
 * generated by Xtext 2.24.0
 */
package entities.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityDslRuntimeModule extends AbstractEntityDslRuntimeModule {
}
