/*
 * generated by Xtext 2.24.0
 */
package entities.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEntityDslScopeProvider extends DelegatingScopeProvider {
}
