/*
 * generated by Xtext 2.24.0
 */
package entities.dsl.ui.tests;

import com.google.inject.Injector;
import entities.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EntityDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("entities.dsl.EntityDsl");
	}

}
