/*
 * generated by Xtext 2.24.0
 */
package entities.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EntityDslUiModule extends AbstractEntityDslUiModule {

	public EntityDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
